2020-06-07 00:05:19.213 | INFO     | __main__:login:160 - User 'admin@admin.com' successfully logged in
2020-06-07 00:05:49.495 | INFO     | __main__:change_password:105 - Changed password for user admin@admin.com
2020-06-07 00:06:40.089 | INFO     | __main__:create_project:193 - Successfully created project test-project
2020-06-07 00:16:36.582 | INFO     | __main__:create_user_story:237 - Successfully created user-story/feature 'create_upload_expense'
2020-06-07 00:18:32.043 | INFO     | __main__:create_user_story:237 - Successfully created user-story/feature 'create_upload_expense'
2020-06-07 00:18:32.070 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'manipulate expense information'
2020-06-07 00:18:32.082 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'tag-expense-to-someone-else'
2020-06-07 00:18:32.093 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'bring-down-the-system-malware'
2020-06-07 00:40:55.577 | INFO     | __main__:create_user_story:237 - Successfully created user-story/feature 'create_upload_expense'
2020-06-07 00:40:55.586 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'manipulate expense information'
2020-06-07 00:40:55.595 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'tag-expense-to-someone-else'
2020-06-07 00:40:55.604 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'bring-down-the-system-malware'
2020-06-07 01:31:00.163 | INFO     | __main__:create_user_story:237 - Successfully created user-story/feature 'create_upload_expense'
2020-06-07 01:31:00.173 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'manipulate expense information'
2020-06-07 01:31:00.182 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'tag-expense-to-someone-else'
2020-06-07 01:31:00.191 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'bring-down-the-system-malware'
2020-06-07 01:32:16.094 | INFO     | __main__:create_user_story:237 - Successfully created user-story/feature 'create_upload_expense'
2020-06-07 01:32:16.103 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'manipulate expense information'
2020-06-07 01:32:16.113 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'tag-expense-to-someone-else'
2020-06-07 01:32:16.122 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'bring-down-the-system-malware'
2020-06-07 01:32:16.392 | INFO     | __main__:create_threat_scenario:454 - Created Threat Scenario 'upload-malware'
2020-06-07 01:32:16.406 | INFO     | __main__:create_threat_scenario:454 - Created Threat Scenario 'leverage vulnerable component'
2020-06-07 07:38:53.227 | INFO     | __main__:create_user_story:237 - Successfully created user-story/feature 'create_upload_expense'
2020-06-07 07:38:53.255 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'manipulate expense information'
2020-06-07 07:38:53.267 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'tag-expense-to-someone-else'
2020-06-07 07:38:53.279 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'bring-down-the-system-malware'
2020-06-07 07:38:53.550 | INFO     | __main__:create_threat_scenario:454 - Created Threat Scenario 'upload-malware'
2020-06-07 07:38:53.563 | INFO     | __main__:create_threat_scenario:454 - Created Threat Scenario 'leverage vulnerable component'
2020-06-07 07:38:53.574 | INFO     | __main__:create_test_case:526 - Created Test-Case 'manual-pentesting' for Threat Scenario 'upload-malware'
2020-06-07 07:38:53.585 | INFO     | __main__:create_test_case:526 - Created Test-Case 'automated-testing' for Threat Scenario 'leverage vulnerable component'
2020-06-19 15:25:51.368 | INFO     | __main__:login:158 - User 'admin@admin.com' successfully logged in
2020-06-19 15:26:45.593 | INFO     | __main__:create_project:191 - Successfully created project we45
2020-06-19 15:27:34.413 | INFO     | __main__:create_user_story:236 - Successfully created user-story/feature 'create_upload_expense'
2020-06-19 15:27:34.451 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'manipulate expense information'
2020-06-19 15:27:34.469 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'tag-expense-to-someone-else'
2020-06-19 15:27:34.487 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'bring-down-the-system-malware'
2020-06-19 15:27:34.898 | INFO     | __main__:create_threat_scenario:456 - Created Threat Scenario 'upload-malware'
2020-06-19 15:27:34.917 | INFO     | __main__:create_threat_scenario:456 - Created Threat Scenario 'leverage vulnerable component'
2020-06-19 15:27:34.932 | INFO     | __main__:create_test_case:529 - Created Test-Case 'manual-pentesting' for Threat Scenario 'upload-malware'
2020-06-19 15:27:34.947 | INFO     | __main__:create_test_case:529 - Created Test-Case 'automated-testing' for Threat Scenario 'leverage vulnerable component'
2020-06-20 21:24:44.474 | ERROR    | __main__:delete_scenario:1582 - Cannot resolve field "name"
2020-06-20 21:25:39.183 | ERROR    | __main__:delete_scenario:1582 - ThreatModel matching query does not exist.
2020-06-20 21:29:31.968 | ERROR    | __main__:delete_abuse_case:1565 - name 'Use' is not defined
2020-06-20 21:30:24.833 | ERROR    | __main__:delete_abuse_case:1565 - Cannot resolve field "name"
2020-06-21 12:31:29.575 | INFO     | __main__:create_project:191 - Successfully created project test-project
2020-06-21 12:31:37.992 | INFO     | __main__:create_user_story:236 - Successfully created user-story/feature 'create_upload_expense'
2020-06-21 12:31:38.007 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'manipulate expense information'
2020-06-21 12:31:38.026 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'tag-expense-to-someone-else'
2020-06-21 12:31:38.041 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'bring-down-the-system-malware'
2020-06-21 12:31:38.372 | ERROR    | __main__:create_threat_scenario:464 - 'dict' object has no attribute 'categories'
Traceback (most recent call last):
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x10b8959d8>
    └ <Thread(Thread-15, started daemon 123145438384128)>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x10b8957b8>
    └ <Thread(Thread-15, started daemon 123145438384128)>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-15, started daemon 123145438384128)>
    │    │        │    └ (<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=('...
    │    │        └ <Thread(Thread-15, started daemon 123145438384128)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x10ce56240>>
    └ <Thread(Thread-15, started daemon 123145438384128)>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60767)
    │    │              └ <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x10c0bf400>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10ce56240>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x10ce56240>
    │    │                   │        └ ('127.0.0.1', 60767)
    │    │                   └ <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=('1...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10ce56240>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x10c28c9d8>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10ce56f60>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
    │                      │      └ <werkzeug.serving.WSGIRequestHandler object at 0x10ce56f60>
    │                      └ <function BaseHTTPRequestHandler.handle at 0x10c1d3158>
    └ <class 'http.server.BaseHTTPRequestHandler'>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x10c28cb70>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10ce56f60>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 379, in handle_one_request
    return self.run_wsgi()
           │    └ <function WSGIRequestHandler.run_wsgi at 0x10c28c950>
           └ <werkzeug.serving.WSGIRequestHandler object at 0x10ce56f60>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x10cde7550>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10ce56240>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x10ce56f60>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x10ce8aa60>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x10ce651b0>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/debug/__init__.py", line 304, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x10ce8a8c8>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=9>, 'wsgi.errors': <_io.TextIOWrap...
               │    └ <Flask 'app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x10cde7550>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x10ce8a8c8>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=9>, 'wsgi.errors': <_io.TextIOWrap...
           │    └ <function Flask.wsgi_app at 0x10c4e5268>
           └ <Flask 'app'>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x10c4e3950>
               └ <Flask 'app'>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x10c4e38c8>
         └ <Flask 'app'>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
           │    │              │    │           │   └ {}
           │    │              │    │           └ <Request 'http://localhost:5000/scenario/create' [POST]>
           │    │              │    └ 'create_threat_scenario'
           │    │              └ <Rule '/scenario/create' (OPTIONS, POST) -> create_threat_scenario>
           │    └ {'static': <bound method _PackageBoundObject.send_static_file of <Flask 'app'>>, 'flasgger.static': <bound method _PackageBou...
           └ <Flask 'app'>

  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/tp_api/app.py", line 48, in inner
    return f(*args, **kwargs)
           │  │       └ {}
           │  └ ()
           └ <function create_threat_scenario at 0x10cdc7950>

  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flasgger/utils.py", line 255, in wrapper
    return function(*args, **kwargs)
           │         │       └ {}
           │         └ ()
           └ <function create_threat_scenario at 0x10cdc78c8>

> File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/tp_api/app.py", line 442, in create_threat_scenario
    for single_category in data.categories:
                           └ {'name': 'upload-malware', 'feature': 'create_upload_expense', 'abuser_story': 'bring-down-the-system-malware', 'description'...

AttributeError: 'dict' object has no attribute 'categories'
2020-06-21 12:31:38.404 | ERROR    | __main__:create_threat_scenario:464 - 'dict' object has no attribute 'categories'
Traceback (most recent call last):
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x10b8959d8>
    └ <Thread(Thread-16, started daemon 123145438384128)>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x10b8957b8>
    └ <Thread(Thread-16, started daemon 123145438384128)>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-16, started daemon 123145438384128)>
    │    │        │    └ (<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=('...
    │    │        └ <Thread(Thread-16, started daemon 123145438384128)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x10ce56240>>
    └ <Thread(Thread-16, started daemon 123145438384128)>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60769)
    │    │              └ <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x10c0bf400>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10ce56240>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x10ce56240>
    │    │                   │        └ ('127.0.0.1', 60769)
    │    │                   └ <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=('1...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10ce56240>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x10c28c9d8>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10ce5f358>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
    │                      │      └ <werkzeug.serving.WSGIRequestHandler object at 0x10ce5f358>
    │                      └ <function BaseHTTPRequestHandler.handle at 0x10c1d3158>
    └ <class 'http.server.BaseHTTPRequestHandler'>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x10c28cb70>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10ce5f358>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 379, in handle_one_request
    return self.run_wsgi()
           │    └ <function WSGIRequestHandler.run_wsgi at 0x10c28c950>
           └ <werkzeug.serving.WSGIRequestHandler object at 0x10ce5f358>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x10cde7550>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10ce56240>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x10ce5f358>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x10ce8abf8>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x10cec5750>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/debug/__init__.py", line 304, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x10ce8ab70>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=9>, 'wsgi.errors': <_io.TextIOWrap...
               │    └ <Flask 'app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x10cde7550>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x10ce8ab70>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=9>, 'wsgi.errors': <_io.TextIOWrap...
           │    └ <function Flask.wsgi_app at 0x10c4e5268>
           └ <Flask 'app'>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x10c4e3950>
               └ <Flask 'app'>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x10c4e38c8>
         └ <Flask 'app'>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
           │    │              │    │           │   └ {}
           │    │              │    │           └ <Request 'http://localhost:5000/scenario/create' [POST]>
           │    │              │    └ 'create_threat_scenario'
           │    │              └ <Rule '/scenario/create' (OPTIONS, POST) -> create_threat_scenario>
           │    └ {'static': <bound method _PackageBoundObject.send_static_file of <Flask 'app'>>, 'flasgger.static': <bound method _PackageBou...
           └ <Flask 'app'>

  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/tp_api/app.py", line 48, in inner
    return f(*args, **kwargs)
           │  │       └ {}
           │  └ ()
           └ <function create_threat_scenario at 0x10cdc7950>

  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flasgger/utils.py", line 255, in wrapper
    return function(*args, **kwargs)
           │         │       └ {}
           │         └ ()
           └ <function create_threat_scenario at 0x10cdc78c8>

> File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/tp_api/app.py", line 442, in create_threat_scenario
    for single_category in data.categories:
                           └ {'name': 'leverage vulnerable component', 'feature': 'create_upload_expense', 'abuser_story': 'bring-down-the-system-malware'...

AttributeError: 'dict' object has no attribute 'categories'
2020-06-21 12:31:38.429 | INFO     | __main__:create_test_case:530 - Created Test-Case 'manual-pentesting' for Threat Scenario 'upload-malware'
2020-06-21 12:31:38.442 | INFO     | __main__:create_test_case:530 - Created Test-Case 'manual-pentesting' for Threat Scenario 'upload-malware'
2020-06-21 12:31:38.463 | INFO     | __main__:create_test_case:530 - Created Test-Case 'automated-testing' for Threat Scenario 'leverage vulnerable component'
2020-06-21 12:31:38.482 | INFO     | __main__:create_test_case:530 - Created Test-Case 'automated-testing' for Threat Scenario 'leverage vulnerable component'
2020-06-21 12:36:07.917 | ERROR    | __main__:get_project:768 - Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/mongoengine/queryset/base.py", line 259, in get
    result = six.next(queryset)
             │   │    └ []
             │   └ <built-in function next>
             └ <module 'six' from '/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/six.py'>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/mongoengine/queryset/base.py", line 1574, in __next__
    raw_doc = six.next(self._cursor)
              │   │    │    └ <property object at 0x10b7ba098>
              │   │    └ []
              │   └ <built-in function next>
              └ <module 'six' from '/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/six.py'>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/pymongo/cursor.py", line 1164, in next
    raise StopIteration

StopIteration


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x10a7c39d8>
    └ <Thread(Thread-2, started daemon 123145424842752)>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x10a7c37b8>
    └ <Thread(Thread-2, started daemon 123145424842752)>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2, started daemon 123145424842752)>
    │    │        │    └ (<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=('...
    │    │        └ <Thread(Thread-2, started daemon 123145424842752)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x10bd82208>>
    └ <Thread(Thread-2, started daemon 123145424842752)>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60867)
    │    │              └ <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x10afeb400>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10bd82208>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x10bd82208>
    │    │                   │        └ ('127.0.0.1', 60867)
    │    │                   └ <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=('1...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10bd82208>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x10b1ba9d8>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10bd82f98>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
    │                      │      └ <werkzeug.serving.WSGIRequestHandler object at 0x10bd82f98>
    │                      └ <function BaseHTTPRequestHandler.handle at 0x10b100158>
    └ <class 'http.server.BaseHTTPRequestHandler'>
  File "/Users/abhaybhargav/.pyenv/versions/3.7.3/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x10b1bab70>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10bd82f98>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 379, in handle_one_request
    return self.run_wsgi()
           │    └ <function WSGIRequestHandler.run_wsgi at 0x10b1ba950>
           └ <werkzeug.serving.WSGIRequestHandler object at 0x10bd82f98>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x10bd15550>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x10bd82208>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x10bd82f98>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x10bdb7950>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x10bd921b0>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/werkzeug/debug/__init__.py", line 304, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x10bdb78c8>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=9>, 'wsgi.errors': <_io.TextIOWrap...
               │    └ <Flask 'app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x10bd15550>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x10bdb78c8>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=9>, 'wsgi.errors': <_io.TextIOWrap...
           │    └ <function Flask.wsgi_app at 0x10b412268>
           └ <Flask 'app'>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x10b410950>
               └ <Flask 'app'>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x10b4108c8>
         └ <Flask 'app'>
  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
           │    │              │    │           │   └ {}
           │    │              │    │           └ <Request 'http://localhost:5000/project/read' [POST]>
           │    │              │    └ 'get_project'
           │    │              └ <Rule '/project/read' (POST, OPTIONS, HEAD, GET) -> get_project>
           │    └ {'static': <bound method _PackageBoundObject.send_static_file of <Flask 'app'>>, 'flasgger.static': <bound method _PackageBou...
           └ <Flask 'app'>

  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/tp_api/app.py", line 48, in inner
    return f(*args, **kwargs)
           │  │       └ {}
           │  └ ()
           └ <function get_project at 0x10bcfb7b8>

  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/flasgger/utils.py", line 255, in wrapper
    return function(*args, **kwargs)
           │         │       └ {}
           │         └ ()
           └ <function get_project at 0x10bcfb730>

> File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/tp_api/app.py", line 763, in get_project
    Project.objects.get(name=data.get("name")).to_json()
    │       │                │    └ <method 'get' of 'dict' objects>
    │       │                └ {'name': 'test-project'}
    │       └ <mongoengine.queryset.manager.QuerySetManager object at 0x10b9a1320>
    └ <class 'models.Project'>

  File "/Users/abhaybhargav/Documents/code/python/ThreatPlaybook/apiv2/venv/lib/python3.7/site-packages/mongoengine/queryset/base.py", line 262, in get
    raise queryset._document.DoesNotExist(msg)
          │        │         │            └ 'Project matching query does not exist.'
          │        │         └ <class 'models.DoesNotExist'>
          │        └ <class 'models.Project'>
          └ []

models.DoesNotExist: Project matching query does not exist.
2020-06-21 12:36:13.962 | INFO     | __main__:create_project:191 - Successfully created project test-project
2020-06-21 12:36:16.746 | INFO     | __main__:create_user_story:236 - Successfully created user-story/feature 'create_upload_expense'
2020-06-21 12:36:16.761 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'manipulate expense information'
2020-06-21 12:36:16.779 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'tag-expense-to-someone-else'
2020-06-21 12:36:16.796 | INFO     | __main__:create_abuser_story:288 - Successfully created abuser-story 'bring-down-the-system-malware'
2020-06-21 12:36:17.164 | INFO     | __main__:create_threat_scenario:456 - Created Threat Scenario 'upload-malware'
2020-06-21 12:36:17.181 | INFO     | __main__:create_threat_scenario:456 - Created Threat Scenario 'leverage vulnerable component'
2020-06-21 12:36:17.197 | INFO     | __main__:create_test_case:530 - Created Test-Case 'manual-pentesting' for Threat Scenario 'upload-malware'
2020-06-21 12:36:17.216 | INFO     | __main__:create_test_case:530 - Created Test-Case 'automated-testing' for Threat Scenario 'leverage vulnerable component'
2020-06-21 12:43:05.703 | ERROR    | __main__:create_scan:627 - Tried to save duplicate unique keys (E11000 duplicate key error collection: threat_playbook.scan index: name_1 dup key: { name: null })
2020-06-21 12:44:01.364 | ERROR    | __main__:create_scan:627 - Tried to save duplicate unique keys (E11000 duplicate key error collection: threat_playbook.scan index: name_1 dup key: { name: null })
2020-06-21 12:44:19.141 | ERROR    | __main__:create_scan:627 - Tried to save duplicate unique keys (E11000 duplicate key error collection: threat_playbook.scan index: name_1 dup key: { name: null })
2020-06-21 12:50:40.291 | ERROR    | __main__:create_scan:627 - 'Test object' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
2020-06-21 12:51:28.458 | ERROR    | __main__:create_scan:627 - 'Test object' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
2020-06-21 12:52:06.713 | ERROR    | __main__:create_scan:627 - 'Test object' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
2020-06-21 12:52:47.927 | ERROR    | __main__:create_scan:627 - name 'ref_scan' is not defined
